kind: pipeline
name: build-amd64

platform:
  arch: amd64

steps:
- name: test
  image: rust:1.47
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all

---
kind: pipeline
name: build-arm64

platform:
  arch: arm64

steps:
- name: test
  image: rust:1.47
  commands:
  - cargo build --verbose --all